// Curly Girl Wavy Girl UK — Product Database
// 286 CGM-reviewed products from UK retailers
// Structure: window.CG_PRODUCTS global for file:// compatibility
// Source: research-uk-products-expanded.md (2026-02-15)

window.CG_PRODUCTS = [
  // ===== BUDGET: POUNDLAND / SAVERS (from 99p) =====
  { id: 1, name: "XHC Banana Conditioner 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["holy-grail", "budget-starter", "co-wash"], notes: "Holy grail budget co-wash. Silicone-free, sulphate-free." },
  { id: 2, name: "XHC Strawberry Conditioner 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Silicone-free, sulphate-free." },
  { id: 3, name: "XHC Green Tea Conditioner 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Silicone-free." },
  { id: 4, name: "XHC Anti-Dandruff Ginger Conditioner 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Good for flaky scalp." },
  { id: 5, name: "XHC Banana Shampoo 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Contains C14-16 Olefin Sulfonate (gentle clarifier, NOT a sulphate)." },
  { id: 6, name: "XHC Strawberry Shampoo 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "For monthly clarifying." },
  { id: 7, name: "XHC Green Tea Shampoo 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "CG-safe clarifying surfactant." },
  { id: 8, name: "XHC Anti-Dandruff Ginger Shampoo 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Gets rid of buildup." },
  { id: 9, name: "XHC Papaya Vegan Repairing Conditioner 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Vegan, budget-friendly." },
  { id: 10, name: "XHC Papaya Vegan Repairing Shampoo 400ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Sulphate-free, silicone-free." },
  { id: 11, name: "XHC Biotin & Collagen Conditioner 300ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: ["protein-boost"], notes: "Protein boost for fine/thinning hair." },
  { id: 12, name: "XHC No Rinse Conditioner Hydrating Coconut 250ml", brand: "XHC", price: "£1.25", retailer: "Poundland", category: "leave-in", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Budget leave-in." },
  { id: 13, name: "XHC No Rinse Conditioner Nourishing Papaya 250ml", brand: "XHC", price: "£1.25", retailer: "Poundland", category: "leave-in", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Budget leave-in." },
  { id: 14, name: "XHC Frizz Free and Fabulous Serum", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "serum", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: [], notes: "CG safe anti-frizz." },
  { id: 15, name: "XHC Argan Hair Treatment Shots (3 pack)", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "treatment", cgm: "caution", hairType: "all", weight: "medium", tags: [], notes: "Contains water-soluble dimethicone." },
  { id: 16, name: "XHC Therapeutic Shampoo 300ml", brand: "XHC", price: "£1.00", retailer: "Poundland", category: "shampoo", cgm: "caution", hairType: "all", weight: "lightweight", tags: [], notes: "For scalp conditions like psoriasis. Medicated." },

  // ===== BUDGET: SAVERS ADDITIONS =====
  { id: 17, name: "XHC Silver Conditioner 400ml", brand: "XHC", price: "£0.99", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Purple toning + CGM safe. Great for grey/blonde." },
  { id: 18, name: "XHC Silver Treatment Shots (3 pack)", brand: "XHC", price: "£0.99", retailer: "Savers", category: "treatment", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Toning treatment for grey/blonde." },
  { id: 19, name: "Syoss Full Hair 5 Conditioner 500ml", brand: "Syoss", price: "£2.50", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: [], notes: "Volume boost." },
  { id: 20, name: "TRESemme Perfectly (UN)DONE Conditioner 25oz", brand: "TRESemme", price: "£3-4", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["holy-grail-wavies"], notes: "Great for wavy hair." },
  { id: 21, name: "TRESemme Expert Botanique Conditioner", brand: "TRESemme", price: "£3-4", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "92% natural." },
  { id: 22, name: "Garnier Ultimate Blends Delicate Oat Conditioner", brand: "Garnier", price: "£2-3", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: [], notes: "Good for sensitive scalps." },
  { id: 23, name: "Pro:Voke Touch of Silver Conditioner 200ml", brand: "Pro:Voke", price: "£2-3", retailer: "Savers", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Colour-safe toning for grey/blonde." },
  { id: 24, name: "Wella Shockwaves Wet Look Gel 200ml", brand: "Wella", price: "£2.50", retailer: "Savers", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["good-sotc"], notes: "Strong hold, CG safe." },
  { id: 25, name: "Wella Shockwaves Ultra Strong Power Gel 200ml", brand: "Wella", price: "£2.50", retailer: "Savers", category: "gel", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Very strong hold." },
  { id: 26, name: "Wella Shockwaves Tuff Stuff Gel 200ml", brand: "Wella", price: "£2.50", retailer: "Savers", category: "gel", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Strong hold." },
  { id: 27, name: "Studio 2000 Extra Hold Mousse 400ml", brand: "Studio 2000", price: "£1.50", retailer: "Savers", category: "mousse", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["budget-starter"], notes: "Budget mousse." },
  { id: 28, name: "Wella Shockwaves Boost It Heat Defence Mousse 200ml", brand: "Wella", price: "£3", retailer: "Savers", category: "mousse", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Heat protection + CGM." },
  { id: 29, name: "Pantene Mousse No 5", brand: "Pantene", price: "£3-4", retailer: "Savers", category: "mousse", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: [], notes: "Community favourite mousse." },
  { id: 30, name: "Eco Styler Olive Oil Styling Gel 236ml", brand: "Eco Styler", price: "£2.99", retailer: "Savers", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["holy-grail", "good-sotc"], notes: "Holy grail for curlies. Strong hold." },
  { id: 31, name: "Eco Styler Argan Oil Styling Gel 236ml", brand: "Eco Styler", price: "£2.99", retailer: "Savers", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Nourishing hold." },
  { id: 32, name: "Eco Styler Krystal Styling Gel 236ml", brand: "Eco Styler", price: "£2.99", retailer: "Savers", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["good-sotc"], notes: "Clear, no residue." },

  // ===== BUDGET: HOME BARGAINS / B&M =====
  { id: 33, name: "Inecto Naturals Coconut Conditioner 500ml", brand: "Inecto", price: "£1.99", retailer: "Home Bargains", category: "conditioner", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Good if hair likes coconut. Also at B&M." },
  { id: 34, name: "Inecto Naturals Argan Oil Conditioner 500ml", brand: "Inecto", price: "£1.99", retailer: "Home Bargains", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Affordable, large size." },
  { id: 35, name: "Eco Styler Olive Oil Gel 473ml", brand: "Eco Styler", price: "£3.50-4", retailer: "B&M", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["holy-grail"], notes: "Bigger size." },

  // ===== SUPERMARKETS =====
  { id: 36, name: "Tesco Extreme Styling Gel (Green Tub)", brand: "Tesco", price: "£1.50", retailer: "Tesco", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["budget-starter"], notes: "Bargain gel." },
  { id: 37, name: "Tesco Extreme Styling Gel (Blue Tub)", brand: "Tesco", price: "£1.50", retailer: "Tesco", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["budget-starter"], notes: "Bargain gel." },
  { id: 38, name: "Tesco Max Hold Purple Mousse", brand: "Tesco", price: "£1.50", retailer: "Tesco", category: "mousse", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["budget-starter"], notes: "Budget mousse." },
  { id: 39, name: "Tesco Pro Vitamin B5 Care & Protect Conditioner", brand: "Tesco", price: "£1.50", retailer: "Tesco", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Budget option." },
  { id: 40, name: "Tesco Volume & Shine Conditioner", brand: "Tesco", price: "£1.50", retailer: "Tesco", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: [], notes: "Budget volumising." },
  { id: 41, name: "Organic Shop Honey & Avocado Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free mask." },
  { id: 42, name: "Organic Shop Pomegranate & Patchouli Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 43, name: "Organic Shop Argan & Amla Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Moisturising." },
  { id: 44, name: "Organic Shop Raspberry & Acai Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Antioxidant rich." },
  { id: 45, name: "Organic Shop Coconut & Shea Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Deep moisture." },
  { id: 46, name: "Organic Shop Indian Jasmine Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Budget treat." },
  { id: 47, name: "Organic Shop Greek Fig Hair Mask", brand: "Organic Shop", price: "£2.50", retailer: "Tesco", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Budget treat." },
  { id: 48, name: "Sainsbury's Apple Conditioner", brand: "Sainsbury's", price: "£1", retailer: "Sainsbury's", category: "conditioner", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["budget-starter"], notes: "Budget starter." },
  { id: 49, name: "ASDA Apple Conditioner", brand: "ASDA", price: "£1", retailer: "ASDA", category: "conditioner", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["budget-starter"], notes: "Budget co-wash option." },
  { id: 50, name: "Garnier Hair Food Banana Conditioner 400ml", brand: "Garnier", price: "£4.00", retailer: "ASDA", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Often cheaper at Asda." },

  // ===== HIGH STREET: BOOTS =====
  { id: 51, name: "Boots Essentials Gel", brand: "Boots", price: "£0.99", retailer: "Boots", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["holy-grail", "budget-starter", "good-sotc"], notes: "Cheapest gel in UK. 99p. Community holy grail." },
  { id: 52, name: "Boots Essentials Curl Creme 250ml", brand: "Boots", price: "£1.50", retailer: "Boots", category: "curl-cream", cgm: "caution", hairType: "2A-3A", weight: "lightweight", tags: [], notes: "Check current formulation." },
  { id: 53, name: "Shea Moisture Coconut & Hibiscus Curl & Shine Shampoo 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Often on sale." },
  { id: 54, name: "Shea Moisture Coconut & Hibiscus Curl & Shine Conditioner 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["holy-grail"], notes: "Bestseller for type 3-4." },
  { id: 55, name: "Shea Moisture Coconut & Hibiscus Curl Enhancing Smoothie 326ml", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: ["holy-grail"], notes: "Holy grail for type 3-4." },
  { id: 56, name: "Shea Moisture Coconut & Hibiscus Curl Milk 254ml", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "leave-in", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Lightweight-ish for SM." },
  { id: 57, name: "Shea Moisture Coconut & Hibiscus Curl & Shine Hair Masque", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Deep treatment." },
  { id: 58, name: "Shea Moisture Raw Shea Butter Extra-Moisture Retention Shampoo 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "Intense moisture." },
  { id: 59, name: "Shea Moisture Raw Shea Butter Restorative Conditioner 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "Rich formula." },
  { id: 60, name: "Shea Moisture JBCO Strengthen & Restore Shampoo 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["protein-boost"], notes: "Strengthening, protein." },
  { id: 61, name: "Shea Moisture JBCO Strengthen & Restore Conditioner 384ml", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["protein-boost"], notes: "Protein-rich." },
  { id: 62, name: "Shea Moisture JBCO Strengthen & Restore Treatment Masque 355ml", brand: "Shea Moisture", price: "£9.32-13.99", retailer: "Boots", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: ["protein-boost"], notes: "Protein treatment." },
  { id: 63, name: "Shea Moisture JBCO Strengthen & Restore Leave-In 431ml", brand: "Shea Moisture", price: "£9.99-14.99", retailer: "Boots", category: "leave-in", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["protein-boost"], notes: "Protein + moisture." },
  { id: 64, name: "Shea Moisture Manuka Honey & Mafura Oil Conditioner", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "Intense hydration." },
  { id: 65, name: "Shea Moisture Manuka Honey & Mafura Oil Masque 354ml", brand: "Shea Moisture", price: "£12", retailer: "Boots", category: "deep-conditioner", cgm: "caution", hairType: "3B-4C", weight: "heavy", tags: [], notes: "Water-soluble silicone." },
  { id: 66, name: "Shea Moisture 100% Virgin Coconut Oil Shampoo", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Daily hydration." },
  { id: 67, name: "Shea Moisture 100% Virgin Coconut Oil Conditioner", brand: "Shea Moisture", price: "£8.66-12.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Daily moisture." },
  { id: 68, name: "Shea Moisture Baobab & Tea Tree Low Porosity Conditioner", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "low-porosity", weight: "lightweight", tags: ["protein-free"], notes: "Protein-free, designed for low porosity." },
  { id: 69, name: "Shea Moisture Fruit Fusion Coconut Water Weightless Masque", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "deep-conditioner", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Lightweight for SM range." },
  { id: 70, name: "Shea Moisture Power Greens Reconstructor Moringa & Avocado", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "treatment", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-boost"], notes: "Protein boost treatment." },
  { id: 71, name: "Shea Moisture Purple Rice Water Strength + Color Care Masque", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "deep-conditioner", cgm: "approved", hairType: "colour-treated", weight: "medium", tags: [], notes: "Colour protection." },
  { id: 72, name: "Maui Moisture Hydrating Vanilla Shampoo", brand: "Maui Moisture", price: "£6-8", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Shampoos only are CGM safe. Conditioners are NOT." },
  { id: 73, name: "Maui Moisture Lightweight Coconut Milk Shampoo", brand: "Maui Moisture", price: "£6-8", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Good for wavy hair." },
  { id: 74, name: "Maui Moisture Revive & Hydrate + Shea Butter Shampoo", brand: "Maui Moisture", price: "£6-8", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Moisturising." },
  { id: 75, name: "Umberto Giannini Curl Jelly Scrunching Jelly 200ml", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "gel", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: ["holy-grail", "good-sotc"], notes: "UK bestseller, holy grail." },
  { id: 76, name: "Umberto Giannini Curl Jelly XL 500ml", brand: "Umberto Giannini", price: "£12-15", retailer: "Boots", category: "gel", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: ["holy-grail"], notes: "Better value size." },
  { id: 77, name: "Umberto Giannini Curl Whip Activating Mousse 200ml", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "mousse", cgm: "caution", hairType: "2A-3B", weight: "lightweight", tags: [], notes: "Check current formulation." },
  { id: 78, name: "Umberto Giannini Boho Beach Jelly", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "gel", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Beachy waves, great for wavies." },
  { id: 79, name: "Umberto Giannini Curl Jelly Wash Shampoo", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Sulphate-free cleanser." },
  { id: 80, name: "Umberto Giannini Curl Care Conditioner", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Paired with Curl Jelly Wash." },
  { id: 81, name: "Umberto Giannini Bond Repair Curl Oil", brand: "Umberto Giannini", price: "£8-10", retailer: "Boots", category: "oil", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Bond repair technology." },
  { id: 82, name: "Umberto Giannini Frizz Fix Conditioner", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2A-3C", weight: "medium", tags: [], notes: "Contains vegan keratin." },
  { id: 83, name: "Umberto Giannini Bergamot + Lemon Oil Vegan Super Serum", brand: "Umberto Giannini", price: "£8-10", retailer: "Boots", category: "serum", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Anti-frizz serum." },
  { id: 84, name: "Umberto Giannini Flowerology Orange & Rosemary Foaming Volume", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "mousse", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["lightweight"], notes: "Volume mousse for fine/wavy." },
  { id: 85, name: "Umberto Giannini Mermaid Hair Volume Mousse", brand: "Umberto Giannini", price: "£6.50-8", retailer: "Boots", category: "mousse", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["lightweight"], notes: "Volume for fine hair." },
  { id: 86, name: "Cantu Cleansing Cream Shampoo 400ml", brand: "Cantu", price: "£4.99-6.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Sulphate-free." },
  { id: 87, name: "Cantu Hydrating Cream Conditioner 400ml", brand: "Cantu", price: "£4.99-6.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Good slip." },
  { id: 88, name: "Cantu Define & Shine Custard 340g", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Great definition." },
  { id: 89, name: "Cantu Moisturizing Curl Activator Cream", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Lightweight for Cantu." },
  { id: 90, name: "Cantu Comeback Curl Next Day Revitalizer 355ml", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "refresh", cgm: "approved", hairType: "3A-4C", weight: "lightweight", tags: [], notes: "Day 2+ refresh spray." },
  { id: 91, name: "Cantu Twist & Lock Gel 370g", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "gel", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "For twists/locs." },
  { id: 92, name: "Cantu Wave Whip Curling Mousse", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "mousse", cgm: "approved", hairType: "2C-3C", weight: "medium", tags: [], notes: "Mousse option." },
  { id: 93, name: "Cantu Coconut Oil Shine & Hold Mist 237ml", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "spray", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Shine spray." },
  { id: 94, name: "Cantu Leave-In Conditioning Repair Cream", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "leave-in", cgm: "not_approved", hairType: "3A-4C", weight: "heavy", tags: ["warning"], notes: "WARNING: Contains silicone despite rest of Cantu range being CGM. Not approved." },
  { id: 95, name: "Cantu Shea Butter Max Hold Styling Gel", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "JBCO formula." },
  { id: 96, name: "Cantu Complete Conditioning CoWash", brand: "Cantu", price: "£5-7", retailer: "Boots", category: "co-wash", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["protein-boost"], notes: "Protein-rich co-wash." },
  { id: 97, name: "Camille Rose Naturals Clean Rinse Conditioner", brand: "Camille Rose", price: "£12-16", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Gourmet ingredients." },

  // ===== HIGH STREET: BOOTS — NOUGHTY =====
  { id: 98, name: "Noughty To The Rescue Moisture Boost Shampoo 250ml", brand: "Noughty", price: "£6.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "97% natural." },
  { id: 99, name: "Noughty Wave Hello Curl Defining Shampoo 250ml", brand: "Noughty", price: "£6.99", retailer: "Boots", category: "shampoo", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "For wavy/curly." },
  { id: 100, name: "Noughty Rise & Shine Hydrate & Shine Conditioner 250ml", brand: "Noughty", price: "£6.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Daily moisture." },
  { id: 101, name: "Noughty Wave Hello Curl Defining Conditioner 250ml", brand: "Noughty", price: "£6.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Curl definition." },
  { id: 102, name: "Noughty To The Rescue Moisture Boost Conditioner 250ml", brand: "Noughty", price: "£6.99", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Deep moisture." },
  { id: 103, name: "Noughty Intensive Care Leave-in Conditioner 150ml", brand: "Noughty", price: "£6.99-8.99", retailer: "Boots", category: "leave-in", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 104, name: "Noughty Wave Hello Curl Defining Taming Cream 150ml", brand: "Noughty", price: "£6.99-8.99", retailer: "Boots", category: "curl-cream", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "For wavy types." },
  { id: 105, name: "Noughty Frizz Magic Anti-Frizz Serum 75ml", brand: "Noughty", price: "£8.99-10.99", retailer: "Boots", category: "serum", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Frizz control." },
  { id: 106, name: "Noughty To The Rescue Intense Moisture Treatment 300ml", brand: "Noughty", price: "£11.99", retailer: "Boots", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Weekly treatment." },

  // ===== HIGH STREET: BOOTS — FAITH IN NATURE =====
  { id: 107, name: "Faith in Nature Aloe Vera Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["protein-free"], notes: "Protein-free. 5L refill available." },
  { id: 108, name: "Faith in Nature Coconut Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: ["protein-free"], notes: "If hair likes coconut. 5L refill." },
  { id: 109, name: "Faith in Nature Dragon Fruit Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Vegan, cruelty-free." },
  { id: 110, name: "Faith in Nature Lavender & Geranium Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 111, name: "Faith in Nature Tea Tree Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "oily-scalp", weight: "lightweight", tags: [], notes: "Clarifying." },
  { id: 112, name: "Faith in Nature Watermelon Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 113, name: "Faith in Nature Wild Rose Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 114, name: "Faith in Nature Hemp & Meadowfoam Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "Heavy moisture." },
  { id: 115, name: "Faith in Nature Jojoba Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 116, name: "Faith in Nature Lemon & Tea Tree Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "oily-scalp", weight: "lightweight", tags: [], notes: "Clarifying." },
  { id: 117, name: "Faith in Nature Fragrance Free Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "sensitive", weight: "lightweight", tags: ["fragrance-free"], notes: "Fragrance-free option." },
  { id: 118, name: "Faith in Nature Pomegranate Conditioner", brand: "Faith in Nature", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "not_approved", hairType: "all", weight: "medium", tags: ["warning"], notes: "Only non-CGM Faith in Nature conditioner." },

  // ===== HIGH STREET: SUPERDRUG =====
  { id: 119, name: "Superdrug Fruity Coconut Conditioner 535ml", brand: "Superdrug", price: "£2.49", retailer: "Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Budget option, large size." },
  { id: 120, name: "Superdrug Fruity Cherry & Almond Conditioner 535ml", brand: "Superdrug", price: "£2.49", retailer: "Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Budget option." },
  { id: 121, name: "Superdrug Revive Purple Conditioner", brand: "Superdrug", price: "£2.50", retailer: "Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Toning for grey/blonde." },
  { id: 122, name: "Superdrug Hair Mousse Firm Hold 300ml", brand: "Superdrug", price: "£2", retailer: "Superdrug", category: "mousse", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["budget-starter"], notes: "Budget mousse." },
  { id: 123, name: "Superdrug Hair Mousse Extra Firm Hold 300ml", brand: "Superdrug", price: "£2", retailer: "Superdrug", category: "mousse", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Stronger hold." },
  { id: 124, name: "Superdrug Black Castor & Shea Curl Cream 250ml", brand: "Superdrug", price: "£3.50", retailer: "Superdrug", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Budget curl cream." },

  // ===== HIGH STREET: SUPERDRUG — IMBUE =====
  { id: 125, name: "Imbue Curl Liberating Sulphate Free Shampoo 400ml", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "100% CGM compliant." },
  { id: 126, name: "Imbue Curl Respecting Conditioner 400ml", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "CGM compliant." },
  { id: 127, name: "Imbue Curl Empowering Creme Gel", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "gel", cgm: "approved", hairType: "2C-3C", weight: "medium", tags: [], notes: "Styling gel." },
  { id: 128, name: "Imbue Curl Inspiring Conditioning Leave-In Spray", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "leave-in", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Spray leave-in." },
  { id: 129, name: "Imbue Curl Defending Heat Protection Mist", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "heat-protectant", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "CGM safe heat protection." },
  { id: 130, name: "Imbue Coil Awakening Sulphate Free Cream Cleanser 400ml", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "co-wash", cgm: "approved", hairType: "3C-4C", weight: "heavy", tags: [], notes: "For coily hair." },
  { id: 131, name: "Imbue Coil Rejoicing Leave In Conditioner 400ml", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "leave-in", cgm: "approved", hairType: "3C-4C", weight: "heavy", tags: [], notes: "For coily hair." },
  { id: 132, name: "Imbue Restoring Intensive Mask", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Weekly treatment." },
  { id: 133, name: "Imbue Energising Hydration Serum", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "serum", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Hydrating serum." },
  { id: 134, name: "Imbue Worshipping Shine Oil", brand: "Imbue", price: "£8.99", retailer: "Superdrug", category: "oil", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Finishing oil." },

  // ===== HIGH STREET: SUPERDRUG — AS I AM =====
  { id: 135, name: "As I Am Smoothing Styling Gel 227g", brand: "As I Am", price: "£8-10", retailer: "Superdrug", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Strong hold." },
  { id: 136, name: "As I Am Coconut CoWash Cleansing Conditioner", brand: "As I Am", price: "£8-10", retailer: "Superdrug", category: "co-wash", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["protein-free"], notes: "Protein-free co-wash." },
  { id: 137, name: "As I Am Leave-In Conditioner 237ml", brand: "As I Am", price: "£8-10", retailer: "Superdrug", category: "leave-in", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Natural formula." },
  { id: 138, name: "As I Am Hydration Elation Intensive Conditioner", brand: "As I Am", price: "£8-10", retailer: "Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Intensive moisture." },
  { id: 139, name: "As I Am Dry & Itchy Scalp Care Co Wash", brand: "As I Am", price: "£8-10", retailer: "Superdrug", category: "co-wash", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Tea tree oil for itchy scalp." },
  { id: 140, name: "As I Am Restore & Repair JBCO Masque", brand: "As I Am", price: "£10-12", retailer: "Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "damaged", weight: "heavy", tags: ["protein-boost"], notes: "Protein treatment." },

  // ===== ONLINE: AMAZON UK =====
  { id: 141, name: "Umberto Giannini Curl Jelly & Foam Mousse Duo", brand: "Umberto Giannini", price: "£17.90", retailer: "Amazon UK", category: "set", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Bestselling duo." },
  { id: 142, name: "Umberto Giannini Wash & Style Essentials Kit (5 products)", brand: "Umberto Giannini", price: "£30", retailer: "Amazon UK", category: "set", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Complete starter kit." },
  { id: 143, name: "Cantu Shea Butter Curl Starter Kit", brand: "Cantu", price: "£15-20", retailer: "Amazon UK", category: "set", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "4-piece set." },

  // ===== PREMIUM: CURLSMITH =====
  { id: 144, name: "Curlsmith Curl Quenching Conditioning Wash", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "co-wash", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Gentle cleanser." },
  { id: 145, name: "Curlsmith Essential Moisture Shampoo", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Daily shampoo." },
  { id: 146, name: "Curlsmith Core Strength Shampoo", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "damaged", weight: "medium", tags: ["protein-boost"], notes: "Protein-rich." },
  { id: 147, name: "Curlsmith Full Body Weightless Shampoo", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Volume, for wavies." },
  { id: 148, name: "Curlsmith Frizz Control Shampoo", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Anti-frizz." },
  { id: 149, name: "Curlsmith Curl Reset Detox Shampoo", brand: "Curlsmith", price: "£23", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Monthly reset/clarifying." },
  { id: 150, name: "Curlsmith Fragrance-Free Shampoo", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "shampoo", cgm: "approved", hairType: "sensitive", weight: "medium", tags: ["fragrance-free"], notes: "No fragrance." },
  { id: 151, name: "Curlsmith Multi-Tasking Conditioner", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "All-rounder." },
  { id: 152, name: "Curlsmith Double Cream Deep Quencher", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Intense moisture." },
  { id: 153, name: "Curlsmith Essential Moisture Conditioner", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Daily conditioner." },
  { id: 154, name: "Curlsmith Full Body Milk Conditioner", brand: "Curlsmith", price: "£22", retailer: "Curlsmith / LookFantastic", category: "conditioner", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Won't weigh down fine/wavy." },
  { id: 155, name: "Curlsmith Weightless Air Dry Cream", brand: "Curlsmith", price: "£23", retailer: "Curlsmith / LookFantastic", category: "leave-in", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["lightweight"], notes: "Air dry styling." },
  { id: 156, name: "Curlsmith Hydro Style Flexi Jelly", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Flexible hold." },
  { id: 157, name: "Curlsmith Curl Defining Styling Souffle", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Definition." },
  { id: 158, name: "Curlsmith Hold Me Softly Style Balm", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "styling", cgm: "approved", hairType: "2A-3B", weight: "medium", tags: [], notes: "Soft hold." },
  { id: 159, name: "Curlsmith Bouncy Strength Volume Foam", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "mousse", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Volume + hold. Great for wavies." },
  { id: 160, name: "Curlsmith Feather-Light Protein Cream", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "treatment", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["protein-boost", "lightweight"], notes: "Protein without weight." },
  { id: 161, name: "Curlsmith Effortless Waves", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "styling", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Specifically designed for waves." },
  { id: 162, name: "Curlsmith Bond Curl Rehab Salve", brand: "Curlsmith", price: "£25", retailer: "Curlsmith / LookFantastic", category: "treatment", cgm: "approved", hairType: "damaged", weight: "heavy", tags: [], notes: "Bond repair treatment." },
  { id: 163, name: "Curlsmith Fragrance-Free Strong Hold Gel", brand: "Curlsmith", price: "£24", retailer: "Curlsmith / LookFantastic", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["fragrance-free"], notes: "No fragrance." },

  // ===== PREMIUM: BOUCLEME =====
  { id: 164, name: "Boucleme Curl Cleanser 300ml", brand: "Boucleme", price: "£18-22", retailer: "Boucleme / Boots", category: "co-wash", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "British brand. Low-lather cleanser." },
  { id: 165, name: "Boucleme Curl Conditioner 300ml", brand: "Boucleme", price: "£20-25", retailer: "Boucleme / Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Nourishing." },
  { id: 166, name: "Boucleme Curl Cream 300ml", brand: "Boucleme", price: "£20-25", retailer: "Boucleme / Boots", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Definition + moisture." },
  { id: 167, name: "Boucleme Curl Defining Gel 300ml", brand: "Boucleme", price: "£15-20", retailer: "Boucleme / Boots", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Strong hold." },
  { id: 168, name: "Boucleme Intensive Moisture Treatment", brand: "Boucleme", price: "£22-28", retailer: "Boucleme / Boots", category: "deep-conditioner", cgm: "approved", hairType: "dry", weight: "heavy", tags: [], notes: "Weekly intensive." },
  { id: 169, name: "Boucleme Super Hold Styler", brand: "Boucleme", price: "£18-22", retailer: "Boucleme / Boots", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Maximum hold." },
  { id: 170, name: "Boucleme Fragrance-Free Curl Cleanser", brand: "Boucleme", price: "£18-22", retailer: "Boucleme / Boots", category: "co-wash", cgm: "approved", hairType: "sensitive", weight: "medium", tags: ["fragrance-free"], notes: "No fragrance." },
  { id: 171, name: "Boucleme Fragrance-Free Curl Conditioner", brand: "Boucleme", price: "£20-25", retailer: "Boucleme / Boots", category: "conditioner", cgm: "approved", hairType: "sensitive", weight: "medium", tags: ["fragrance-free"], notes: "No fragrance." },
  { id: 172, name: "Boucleme Fragrance-Free Curl Defining Gel", brand: "Boucleme", price: "£15-20", retailer: "Boucleme / Boots", category: "gel", cgm: "approved", hairType: "sensitive", weight: "medium", tags: ["fragrance-free"], notes: "No fragrance." },

  // ===== PREMIUM: FLORA & CURL =====
  { id: 173, name: "Flora & Curl Rose Water Cream Shampoo 300ml", brand: "Flora & Curl", price: "£15", retailer: "Flora & Curl / LookFantastic", category: "shampoo", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Black-owned British brand. Won't weigh down fine hair." },
  { id: 174, name: "Flora & Curl Rose Water Cream Conditioner 300ml", brand: "Flora & Curl", price: "£18", retailer: "Flora & Curl / LookFantastic", category: "conditioner", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Lightweight hydration." },
  { id: 175, name: "Flora & Curl Rose Water Detangling Lotion 300ml", brand: "Flora & Curl", price: "£16", retailer: "Flora & Curl / LookFantastic", category: "leave-in", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["protein-free", "lightweight"], notes: "Protein-free." },
  { id: 176, name: "Flora & Curl Rose Water Molasses Moisture Mask 300ml", brand: "Flora & Curl", price: "£22", retailer: "Flora & Curl / LookFantastic", category: "deep-conditioner", cgm: "approved", hairType: "2A-3B", weight: "medium", tags: [], notes: "Weekly treatment." },
  { id: 177, name: "Flora & Curl Sweet Hibiscus Curl Activating Lotion 300ml", brand: "Flora & Curl", price: "£16-18", retailer: "Flora & Curl / LookFantastic", category: "curl-cream", cgm: "approved", hairType: "2C-4C", weight: "medium", tags: [], notes: "Curl activation." },
  { id: 178, name: "Flora & Curl Sweet Hibiscus Curl Defining Gel 200ml", brand: "Flora & Curl", price: "£15.99-18", retailer: "Flora & Curl / LookFantastic", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Definition." },
  { id: 179, name: "Flora & Curl Sweet Hibiscus Curl Volumizing Foam", brand: "Flora & Curl", price: "£16-18", retailer: "Flora & Curl / LookFantastic", category: "mousse", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Volume + definition." },
  { id: 180, name: "Flora & Curl Coconut Mint Scalp Refresh Shampoo 300ml", brand: "Flora & Curl", price: "£18", retailer: "Flora & Curl / LookFantastic", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Scalp-focused." },
  { id: 181, name: "Flora & Curl African Citrus Bloom Defined Curls Styling Butter", brand: "Flora & Curl", price: "£18-22", retailer: "Flora & Curl / LookFantastic", category: "styling", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "Rich definition for coily hair." },

  // ===== PREMIUM: INNERSENSE =====
  { id: 182, name: "Innersense Hydrating Cream Hairbath", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Organic. Gentle cleanser." },
  { id: 183, name: "Innersense Color Radiance Daily Conditioner", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "conditioner", cgm: "approved", hairType: "colour-treated", weight: "medium", tags: [], notes: "Colour safe." },
  { id: 184, name: "Innersense Hydrating Hair Masque", brand: "Innersense", price: "£22-28", retailer: "Kiyo Beauty / Curl Care UK", category: "deep-conditioner", cgm: "approved", hairType: "dry", weight: "heavy", tags: [], notes: "Intensive." },
  { id: 185, name: "Innersense I Create Lift Volumizing Foam", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "mousse", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Holy grail for wavies." },
  { id: 186, name: "Innersense I Create Hold Styling Gel", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Flexible hold." },
  { id: 187, name: "Innersense Quiet Calm Curl Control", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Anti-frizz cream." },
  { id: 188, name: "Innersense Sweet Spirit Leave In Conditioner", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "leave-in", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Lightweight leave-in." },
  { id: 189, name: "Innersense Pure Harmony Hairbath", brand: "Innersense", price: "£22-26", retailer: "Kiyo Beauty / Curl Care UK", category: "shampoo", cgm: "approved", hairType: "sensitive", weight: "lightweight", tags: ["fragrance-free"], notes: "Fragrance-free clarifying." },

  // ===== PREMIUM: JESSICURL =====
  { id: 190, name: "Jessicurl Gentle Lather Shampoo 237ml", brand: "Jessicurl", price: "£12-15", retailer: "Jessicurl UK / Kiyo Beauty", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Gentle cleanser." },
  { id: 191, name: "Jessicurl Too Shea! Extra Moisturizing Conditioner 237ml", brand: "Jessicurl", price: "£12-15", retailer: "Jessicurl UK / Kiyo Beauty", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Rich moisture." },
  { id: 192, name: "Jessicurl Aloeba Daily Conditioner 237ml", brand: "Jessicurl", price: "£12-15", retailer: "Jessicurl UK / Kiyo Beauty", category: "conditioner", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: ["lightweight"], notes: "Daily use, lightweight." },
  { id: 193, name: "Jessicurl Deep Conditioning Treatment 237ml", brand: "Jessicurl", price: "£12-15", retailer: "Jessicurl UK / Kiyo Beauty", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "heavy", tags: [], notes: "Weekly treatment." },
  { id: 194, name: "Jessicurl Rockin' Ringlets Styling Potion 237ml", brand: "Jessicurl", price: "£14-17", retailer: "Jessicurl UK / Kiyo Beauty", category: "curl-cream", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Flaxseed-based." },
  { id: 195, name: "Jessicurl Spiralicious Styling Gel 237ml", brand: "Jessicurl", price: "£14-17", retailer: "Jessicurl UK / Kiyo Beauty", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Definition + hold." },
  { id: 196, name: "Jessicurl Confident Coils Styling Solution 237ml", brand: "Jessicurl", price: "£14-17", retailer: "Jessicurl UK / Kiyo Beauty", category: "styling", cgm: "approved", hairType: "3C-4C", weight: "medium", tags: [], notes: "For tight curls/coils." },
  { id: 197, name: "Jessicurl Gelebration Spray 237ml", brand: "Jessicurl", price: "£14-17", retailer: "Jessicurl UK / Kiyo Beauty", category: "spray", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["lightweight"], notes: "Lightest hold spray." },

  // ===== PREMIUM: KINKY-CURLY =====
  { id: 198, name: "Kinky-Curly Knot Today Leave-In Conditioner/Detangler 8oz", brand: "Kinky-Curly", price: "£14-15", retailer: "Kiyo Beauty / Beautizone", category: "leave-in", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: ["holy-grail"], notes: "Cult favourite detangler." },
  { id: 199, name: "Kinky-Curly Curling Custard 8oz", brand: "Kinky-Curly", price: "£18-21", retailer: "Kiyo Beauty / Beautizone", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: ["holy-grail"], notes: "Holy grail for type 3-4." },
  { id: 200, name: "Kinky-Curly Come Clean Natural Moisturizing Shampoo", brand: "Kinky-Curly", price: "£12-15", retailer: "Kiyo Beauty / Beautizone", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Gentle cleanser." },

  // ===== PREMIUM: ONLY CURLS =====
  { id: 201, name: "Only Curls All Curl Cleanser", brand: "Only Curls", price: "£16", retailer: "Only Curls", category: "shampoo", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "London-based, made in UK." },
  { id: 202, name: "Only Curls All Curl Conditioner", brand: "Only Curls", price: "£16", retailer: "Only Curls", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Everyday conditioner." },
  { id: 203, name: "Only Curls Hydrating Curl Creme", brand: "Only Curls", price: "£16", retailer: "Only Curls", category: "curl-cream", cgm: "approved", hairType: "2C-3C", weight: "medium", tags: [], notes: "Definition." },
  { id: 204, name: "Only Curls Enhancing Curl Gel", brand: "Only Curls", price: "£16", retailer: "Only Curls", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Hold + definition." },
  { id: 205, name: "Only Curls Intense Moisture Leave-In Cream", brand: "Only Curls", price: "£16", retailer: "Only Curls", category: "leave-in", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Rich moisture." },

  // ===== PREMIUM: AFROCENCHIX =====
  { id: 206, name: "Afrocenchix Seal Moisture Locking Hair Oil 190ml", brand: "Afrocenchix", price: "£18.80", retailer: "Afrocenchix / Superdrug", category: "oil", cgm: "approved", hairType: "3C-4C", weight: "medium", tags: [], notes: "UK's No.1 Afro hair brand." },
  { id: 207, name: "Afrocenchix Sheen Ultra Hydrating Hair Spray 250ml", brand: "Afrocenchix", price: "£16.80", retailer: "Afrocenchix / Superdrug", category: "spray", cgm: "approved", hairType: "3C-4C", weight: "lightweight", tags: [], notes: "Hydrating mist." },
  { id: 208, name: "Afrocenchix Smooth Natural Moisturising Hair Cream 250ml", brand: "Afrocenchix", price: "£17.80", retailer: "Afrocenchix / Superdrug", category: "curl-cream", cgm: "approved", hairType: "3C-4C", weight: "medium", tags: [], notes: "Daily moisturiser." },
  { id: 209, name: "Afrocenchix Spring Nourishing Twisting Butter 100g", brand: "Afrocenchix", price: "£16.80", retailer: "Afrocenchix / Superdrug", category: "styling", cgm: "approved", hairType: "4A-4C", weight: "heavy", tags: [], notes: "For twists/braids." },
  { id: 210, name: "Afrocenchix Nourish Strengthening Biotin Oil 50ml", brand: "Afrocenchix", price: "£15.99", retailer: "Afrocenchix / Superdrug", category: "oil", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Growth/strength." },

  // ===== MID-RANGE: GARNIER =====
  { id: 211, name: "Garnier Hair Food Banana Conditioner 400ml", brand: "Garnier", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Widely available." },
  { id: 212, name: "Garnier Hair Food Papaya Conditioner 400ml", brand: "Garnier", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "damaged", weight: "medium", tags: ["protein-boost"], notes: "Protein-rich." },
  { id: 213, name: "Garnier Hair Food Coconut Conditioner 400ml", brand: "Garnier", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "If hair likes coconut." },
  { id: 214, name: "Garnier Hair Food Aloe Vera Conditioner 400ml", brand: "Garnier", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["lightweight"], notes: "Lightweight option." },
  { id: 215, name: "Garnier Hair Food Banana 3-in-1 Mask 390ml", brand: "Garnier", price: "£6-8", retailer: "Boots / Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Mask/leave-in/conditioner." },
  { id: 216, name: "Garnier Hair Food Papaya 3-in-1 Mask 390ml", brand: "Garnier", price: "£6-8", retailer: "Boots / Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "damaged", weight: "medium", tags: ["protein-free"], notes: "Protein-free." },
  { id: 217, name: "Garnier Hair Food Coconut 3-in-1 Mask 390ml", brand: "Garnier", price: "£6-8", retailer: "Boots / Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "Deep moisture." },
  { id: 218, name: "Garnier Hair Food Aloe Vera 3-in-1 Mask 390ml", brand: "Garnier", price: "£6-8", retailer: "Boots / Superdrug", category: "deep-conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["lightweight"], notes: "Lightest mask option." },
  { id: 219, name: "Garnier Ultimate Blends Almond Milk & Agave Conditioner", brand: "Garnier", price: "£3-5", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Smoothing." },
  { id: 220, name: "Garnier Ultimate Blends Argan Oil & Cranberry Conditioner", brand: "Garnier", price: "£3-5", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "colour-treated", weight: "medium", tags: [], notes: "Colour care." },
  { id: 221, name: "Garnier Ultimate Blends Cherry Blossom Conditioner", brand: "Garnier", price: "£3-5", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: [], notes: "Shine." },

  // ===== MID-RANGE: TRESEMME =====
  { id: 222, name: "TRESemme Perfectly Undone Conditioner", brand: "TRESemme", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "Great for wavy hair." },
  { id: 223, name: "TRESemme Expert Botanique Coconut & Aloe Conditioner", brand: "TRESemme", price: "£4-6", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "92% natural." },
  { id: 224, name: "TRESemme Pro Pure Light Moisture Conditioner", brand: "TRESemme", price: "£5-7", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: ["lightweight"], notes: "Clean formula." },
  { id: 225, name: "TRESemme Pro Pure Damage Conditioner", brand: "TRESemme", price: "£5-7", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "damaged", weight: "medium", tags: [], notes: "Repair formula." },

  // ===== MID-RANGE: OTHER BRANDS =====
  { id: 226, name: "L'Oreal Elnett Satin Strong Hold Volume Mousse 200ml", brand: "L'Oreal", price: "£4-6", retailer: "Boots / Superdrug", category: "mousse", cgm: "approved", hairType: "2A-3A", weight: "lightweight", tags: [], notes: "Strong hold mousse." },
  { id: 227, name: "L'Oreal Elnett Satin Curl Creme Mousse 200ml", brand: "L'Oreal", price: "£4-6", retailer: "Boots / Superdrug", category: "mousse", cgm: "approved", hairType: "2B-3C", weight: "medium", tags: [], notes: "Curl-specific mousse." },
  { id: 228, name: "VO5 Wet Look Styling Gel 200ml", brand: "VO5", price: "£2-3", retailer: "Boots / Superdrug", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["budget-starter", "good-sotc"], notes: "Budget strong hold." },
  { id: 229, name: "VO5 Firm Hold Styling Gel 200ml", brand: "VO5", price: "£2-3", retailer: "Boots / Superdrug", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["budget-starter"], notes: "Budget option." },
  { id: 230, name: "VO5 Mega Hold Gel", brand: "VO5", price: "£3-5", retailer: "Boots / Superdrug", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Travel size available at £2." },
  { id: 231, name: "Wella Shockwaves Volume Mousse", brand: "Wella", price: "£3", retailer: "Boots / Superdrug", category: "mousse", cgm: "approved", hairType: "2A-2C", weight: "lightweight", tags: ["holy-grail-wavies", "lightweight"], notes: "UV protection, good for wavies." },
  { id: 232, name: "Got2b Twisted Anti Frizz Styling Spray", brand: "Got2b", price: "£4-5", retailer: "Boots / Superdrug", category: "spray", cgm: "approved", hairType: "2A-3B", weight: "lightweight", tags: [], notes: "Anti-frizz spray." },

  // ===== MID-RANGE: GIOVANNI =====
  { id: 233, name: "Giovanni LA Hold Styling Gel", brand: "Giovanni", price: "£6-10", retailer: "TK Maxx / LookFantastic", category: "gel", cgm: "approved", hairType: "all", weight: "medium", tags: ["holy-grail", "glycerin-free", "good-sotc"], notes: "Glycerin-free, great for SOTC. TK Maxx find." },
  { id: 234, name: "Giovanni 50:50 Balanced Conditioner", brand: "Giovanni", price: "£6-10", retailer: "TK Maxx / LookFantastic", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "All-round conditioner." },
  { id: 235, name: "Giovanni 2chic Ultra-Moist Conditioner", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "Avocado + olive oil." },
  { id: 236, name: "Giovanni 2chic Frizz Be Gone Conditioner", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Anti-frizz." },
  { id: 237, name: "Giovanni 2chic Ultra-Revive Conditioner", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "Revitalising." },
  { id: 238, name: "Giovanni Smooth as Silk Conditioner", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: ["protein-boost"], notes: "Protein-rich." },
  { id: 239, name: "Giovanni NutraFix Hair Reconstructor", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "treatment", cgm: "approved", hairType: "damaged", weight: "medium", tags: ["protein-boost"], notes: "Intensive protein treatment." },
  { id: 240, name: "Giovanni Direct Leave-In Treatment Conditioner", brand: "Giovanni", price: "£8-12", retailer: "TK Maxx / LookFantastic", category: "leave-in", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Weightless moisture." },

  // ===== BUDGET: BABY / BASICS =====
  { id: 241, name: "Johnson's Top to Toe Wash", brand: "Johnson's", price: "£2-3", retailer: "Boots / Superdrug", category: "shampoo", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Baby wash, gentle cleanser." },
  { id: 242, name: "Johnson's Shiny Drops Conditioner Spray", brand: "Johnson's", price: "£2-3", retailer: "Boots / Superdrug", category: "leave-in", cgm: "approved", hairType: "fine", weight: "lightweight", tags: ["lightweight"], notes: "Gentle detangler." },
  { id: 243, name: "Alberto Balsam Sun-Kissed Raspberry Conditioner", brand: "Alberto Balsam", price: "£1-1.50", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "all", weight: "lightweight", tags: ["budget-starter"], notes: "Silicone-free budget pick." },

  // ===== MID-RANGE: OTHER =====
  { id: 244, name: "Twisted Sista Amazing Dream Curl Gel 354ml", brand: "Twisted Sista", price: "£5-7", retailer: "Superdrug", category: "gel", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Curl definition." },
  { id: 245, name: "Kind Natured Love Curls Smoothing Conditioner", brand: "Kind Natured", price: "£3-5", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2C-3C", weight: "medium", tags: [], notes: "Curl smoothing." },
  { id: 246, name: "Kind Natured Argan & Fukui Oil Conditioner", brand: "Kind Natured", price: "£3-5", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "all", weight: "medium", tags: [], notes: "Nourishing." },
  { id: 247, name: "Kind Natured Coconut & Shea Conditioner", brand: "Kind Natured", price: "£3-5", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Deep moisture." },
  { id: 248, name: "Yes To Blueberries Smooth & Shine Conditioner", brand: "Yes To", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "2A-3B", weight: "medium", tags: [], notes: "Smoothing." },
  { id: 249, name: "Yes To Cucumber Volumising Conditioner", brand: "Yes To", price: "£4-6", retailer: "Boots", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: ["lightweight"], notes: "Volume." },
  { id: 250, name: "Love Beauty & Planet Volume & Bounty Conditioner", brand: "Love Beauty & Planet", price: "£5-7", retailer: "Boots / Superdrug", category: "conditioner", cgm: "approved", hairType: "fine", weight: "lightweight", tags: ["lightweight"], notes: "Eco packaging." },
  { id: 251, name: "The Body Shop Banana Nourishing Conditioner", brand: "The Body Shop", price: "£8-12", retailer: "The Body Shop", category: "conditioner", cgm: "approved", hairType: "dry", weight: "medium", tags: [], notes: "Rich formula." },
  { id: 252, name: "The Body Shop Ginger Scalp Care Conditioner", brand: "The Body Shop", price: "£8-12", retailer: "The Body Shop", category: "conditioner", cgm: "approved", hairType: "oily-scalp", weight: "lightweight", tags: [], notes: "Scalp care." },
  { id: 253, name: "The Body Shop Shea Butter Conditioner", brand: "The Body Shop", price: "£8-12", retailer: "The Body Shop", category: "conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Rich moisture." },
  { id: 254, name: "ORS Nourish & Seal Coconut Oil", brand: "ORS", price: "£4-6", retailer: "Superdrug / Pak's", category: "oil", cgm: "approved", hairType: "3A-4C", weight: "lightweight", tags: [], notes: "Sealing oil." },
  { id: 255, name: "Shea Moisture Jamaican Black Castor Oil Renewal Lotion", brand: "Shea Moisture", price: "£10-13", retailer: "Boots", category: "leave-in", cgm: "approved", hairType: "3B-4C", weight: "heavy", tags: [], notes: "JBCO formula." },
  { id: 256, name: "Aunt Jackie's Rescued Thirst Quenching Conditioner", brand: "Aunt Jackie's", price: "£8-10", retailer: "Superdrug / Pak's", category: "deep-conditioner", cgm: "approved", hairType: "3A-4C", weight: "heavy", tags: [], notes: "Intensive repair." },
  { id: 257, name: "Aunt Jackie's Purify Me Co-Wash", brand: "Aunt Jackie's", price: "£8-10", retailer: "Superdrug / Pak's", category: "co-wash", cgm: "approved", hairType: "3A-4C", weight: "medium", tags: [], notes: "Clarifying co-wash." }
];

// Discontinued / reformulated products — warn users
window.CG_WARNINGS = [
  { brand: "Tesco Extracts", status: "reformulated", note: "Tesco Extracts conditioners now contain Dimethicone (silicone). No longer CGM approved." },
  { brand: "Superdrug Extracts", status: "discontinued", note: "Replaced by Fruity range (which IS CGM approved)." },
  { brand: "Wilko", status: "discontinued", note: "Wilko closed in 2023. All products unavailable." },
  { brand: "Maui Moisture", status: "caution", note: "Shampoos are CGM approved but NONE of their conditioners are. Only 13/36 products are CGM safe." },
  { brand: "DevaCurl", status: "caution", note: "Hair loss lawsuits in the US. Reformulated. Limited UK availability. Community recommends alternatives." },
  { brand: "Cantu Leave-In Conditioning Repair Cream", status: "not_approved", note: "Contains silicone despite rest of Cantu range being CGM." },
  { brand: "Lidl / Aldi", status: "check_label", note: "Lacura/Cien ranges change formulations without notice. Always check ingredients." }
];

// Tag definitions for display
window.CG_PRODUCT_TAGS = {
  "holy-grail": { label: "Holy Grail", color: "#FFD700", desc: "Universally loved, works for most" },
  "holy-grail-wavies": { label: "Holy Grail (Wavies)", color: "#B8E986", desc: "Specifically loved by 2A-2C" },
  "budget-starter": { label: "Budget Starter", color: "#90EE90", desc: "Under £3, great for trying CGM" },
  "good-sotc": { label: "Good SOTC", color: "#87CEEB", desc: "Scrunch Out The Crunch - breaks easily" },
  "protein-free": { label: "Protein Free", color: "#DDA0DD", desc: "No protein - for protein-sensitive hair" },
  "protein-boost": { label: "Protein Boost", color: "#FFA07A", desc: "Contains protein for strength" },
  "fragrance-free": { label: "Fragrance Free", color: "#D3D3D3", desc: "No added fragrance" },
  "lightweight": { label: "Lightweight", color: "#E0F0FF", desc: "Won't weigh down fine/wavy hair" },
  "glycerin-free": { label: "Glycerin Free", color: "#F0E68C", desc: "No glycerin - for humid climates" },
  "co-wash": { label: "Co-wash", color: "#98FB98", desc: "Can be used as a co-wash" },
  "warning": { label: "Warning", color: "#FF6B6B", desc: "Check notes - may not be CGM approved" }
};
